### ISSUE TITLE
Add generic maintenance page

### ISSUE THREAD

**Issue by coltenkrauter** [guillaumebriday/traefik-custom-error-pages#1]
It would be great if you could add a generic maintenance page that traefik could route to when my app is being updated.

**Comment by coltenkrauter** [comment]
Slaps forehead.... 503. yup, it is there. Thanks

**Comment by guillaumebriday** [comment]
Hey ! 503 error page is present yes but I don’t know how to use it with traefik to be honest. Because as you can see on the readme I only use the 404 page :/

How do you serve 503 page with traefik before your application ?

**Comment by coltenkrauter** [comment]
I don't know just yet... Haha... Hopefully gonna figure that out. I use Traefik to proxy network requests, so I will probably just add a label to the maintenance-page image at the start of my cicd Jenkins build pipeline that routes traffic to the maintenance page and then undoes the routing when the build completes successfully.
