### ISSUE TITLE
Fail2ban

### ISSUE THREAD

**Issue by modem7** [guillaumebriday/traefik-custom-error-pages#14]
Hey guys, 

Unsure if this would be the best place to post, or over at the fail2ban git. 

Looking to try to create a fail2ban filter so block bots trying to crawl the site. Tried the official one for Nginx:

```
# Fail2Ban filter to match web requests for selected URLs that don't exist
#

[INCLUDES]

# Load regexes for filtering
before = botsearch-common.conf

[Definition]

failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/<block> \S+\" 404 .+$
            ^ \[error\] \d+#\d+: \*\d+ (\S+ )?\"\S+\" (failed|is not found) \(2\: No such file or directory\), client\: <HOST>\, server\: \S*\, request: \"(GET|POST|HEAD) \/<block> \S+\"\, .*?$

ignoreregex =

datepattern = {^LN-BEG}%%ExY(?P<_sep>[-/.])%%m(?P=_sep)%%d[T ]%%H:%%M:%%S(?:[.,]%%f)?(?:\s*%%z)?
              ^[^\[]*\[({DATE})
              {^LN-BEG}

# DEV Notes:
# Based on apache-botsearch filter
#

```

But unfortunately this is not picking up the logs from the Nginx error or access logs. 

Just curious if anyone has done this for this container, and if so could share their filter?

**Comment by guillaumebriday** [comment]
Sorry but this issue is not related to this project at all.
