### ISSUE TITLE
How does this work? Can it be implemented to docker-compose?

### ISSUE THREAD

**Issue by thepenguinthatwants** [guillaumebriday/traefik-custom-error-pages#2]
Do you have example traefik docker-compose that shows how to implement this with your error pages?

I tried running

docker run --rm -d guillaumebriday/traefik-custom-error-pages

I only tested this on my localhost laptop and when when I tried nonexisted page like something.localhost  ..  I  just get the Gateway Timeout from traefik.  Localhost has being set to direct into the traefik dashboard.

Also noticed your issue with traefik

```
    labels:
      - "traefik.frontend.rule=HostRegexp:{catchall:.*}"
      - "traefik.frontend.priority=1"

```
Have u found out how to implement it on traefik with your error pages?

**Comment by guillaumebriday** [comment]
Docker-compose use a dedicated network for services declared in the `docker-compose.yml`

If you run `docker run --rm -d guillaumebriday/traefik-custom-error-pages`, this container will be completely unreachable from traffic started in the `docker-compose`.

Try something like that in your `docker-compose.yml` :

```yml
  error-pages:
    image: guillaumebriday/traefik-custom-error-pages
```

Does it work ?

**Comment by thepenguinthatwants** [comment]
I seem to be unable to get this work. I am right now using traefik reverse proxy and thought about adding custom error pages to it.

Is your traefik-custom-error-pages private? I was wondering if its possible to see how its implemented. If I could grasp more and possibly if I get it to work so I might add custom error pages on my own sites.

**Comment by thepenguinthatwants** [comment]
When I implemented on my ghost blog.

I see a random errorpage related warning?

```
Ghost     | [2019-07-12 20:51:15] WARN {{#get}} helper took 523ms to complete
Ghost     | 
Ghost     | {{#get}} helper took 523ms to complete
Ghost     | 
Ghost     | Error ID:
Ghost     |     ca8fdd10-a4e6-11e9-8ec2-53705c595a17
Ghost     | 
Ghost     | Error Code: 
Ghost     |     SLOW_GET_HELPER
Ghost     | 
Ghost     | Details:
Ghost     |     api:          v2.postsPublic.browse
Ghost     |     apiOptions: 
Ghost     |       limit:  1
Ghost     |       filter: featured:true
Ghost     |     returnedRows: 0
Ghost     | 
Ghost     |

Do I need to attach some enviroment variables? How to further test or how should those error pages come?
```
