### ISSUE TITLE
Update Traefik Labels to 2.0

### ISSUE THREAD

**Issue by Kurainu** [guillaumebriday/traefik-custom-error-pages#6]
Hello,
Can you Update the Traefik labels to work with the new Traefik v2 syntax?

**Comment by rafipiccolo** [comment]
I added theses labels and it works
when i call xxx.com i get my website
when i call xxx.com/notfound i get the traefik's beautiful error page
when i kill the xxx container,i get the traefik ugly error page.

    traefik:
        ...
        labels:
            - "traefik.http.middlewares.errorpage.errors.status=404"
            - "traefik.http.middlewares.errorpage.errors.service=errorpage"
            - "traefik.http.middlewares.errorpage.errors.query=/{status}"

    # the service showing beautiful error pages
    errorpage:
        ...
        labels:
            - traefik.enable=true
            - traefik.http.routers.errorpage.rule=Host(`error.xxx.com`)
            - traefik.http.routers.errorpage.tls.certresolver=le
            - traefik.http.routers.errorpage.entrypoints=websecure

    # a custom php website provided with apache, with traefik's default error pages
    xxx:
        ...
        labels:
            - traefik.enable=true
            - traefik.http.routers.xxx.rule=Host(`xxx.com`)
            - traefik.http.routers.xxx.tls.certresolver=le
            - traefik.http.routers.xxx.entrypoints=websecure
            - traefik.http.routers.xxx.middlewares=errorpage

**Comment by Kurainu** [comment]
Oh Thanks for the reply. I try your solution and see if i get it to work for me!
I post my result when i tried it.

**Comment by rafipiccolo** [comment]
hurray, when i add this in traefik i can also replace the ugly default errors (my 3rd point on previous comment)

            - "traefik.http.routers.globalerrorpage.rule=hostregexp(`{host:.+}`)"
            - "traefik.http.routers.globalerrorpage.tls.certresolver=le"
            - "traefik.http.routers.globalerrorpage.entrypoints=websecure"
            - "traefik.http.routers.globalerrorpage.service=errorpage"
            - "traefik.http.routers.globalerrorpage.priority=1"

big old shame on traefik for being so bad on error reporting / documentation / examples...

**Comment by guillaumebriday** [comment]
Nice thanks guys,

I really need to clean up this repo, sorry

**Comment by guillaumebriday** [comment]
Hey guys, here's the update for v2:

https://github.com/guillaumebriday/traefik-custom-error-pages/compare/8bc292af01130552b449508c5fb30b86dbc1e8c2..master

**Comment by guillaumebriday** [comment]
Feel free to reopen if needed 👍
