### ISSUE TITLE
Add 502 - Bad Gateway page

### ISSUE THREAD

**Issue by PolarizedIons** [guillaumebriday/traefik-custom-error-pages#9]
Would be great to have a custom page for a 502 as well.

I would do it myself, but I don't have the artistic skills for the image 😅

**Comment by Heisenberg74** [comment]
Great idea. It could be nice to have kind of destroyed bridge in a desert 😍 with a camel thinking about the awkard situation.

**Comment by guillaumebriday** [comment]
I didn't create this errors pages. They are copied from Laravel 5.7: https://github.com/laravel/framework/tree/5.7/src/Illuminate/Foundation/Exceptions/views and https://github.com/laravel/laravel/tree/5.7/public/svg

You can duplicate one of these and change the error code if needed 👍
